version: '3'
services:
  postgresql:
    image: postgres:12
    restart: always
    container_name: mh-results-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass

volumes:
  postgres-data:
    external: false